# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwf < Formula
  desc "Personal ProWorkflow CLI"
  homepage "https://github.com/Proactive-Software/pwf-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.3/pwf_darwin_amd64.tar.gz"
      sha256 "4da9466d2014e2faec09e0a8bda8617e0f4738b15d033edea7fc4dd34126d298"

      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.3/pwf_darwin_arm64.tar.gz"
      sha256 "16567014fb8f1433c35979632238510bc1b568352a8ed5fbbed62083d6b19413"

      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.3/pwf_linux_amd64.tar.gz"
      sha256 "2934a5c1a2d489abe14c9bee110f0c437d34edb8c3372f823bb2d2ca380c00ca"
      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.3/pwf_linux_arm64.tar.gz"
      sha256 "c09c0bc5b294febc6aa9e0aa5d6e9b97e7148ae6bdb3f6fd4f69285cbeefb164"
      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
  end

  test do
    system "#{bin}/pwf", "--help"
  end
end
