# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwf < Formula
  desc "Personal ProWorkflow CLI"
  homepage "https://github.com/Proactive-Software/pwf-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.2/pwf_darwin_amd64.tar.gz"
      sha256 "79360d5efe011f9b67ba6e41da08d2d2dad8f0cf5a0b4ab8a3ae386c4e5cee53"

      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.2/pwf_darwin_arm64.tar.gz"
      sha256 "d4b6839dbbd7ad51b89aad1bc9c680d57e5c32f9982bd2dae259398426b98a57"

      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.2/pwf_linux_amd64.tar.gz"
      sha256 "f4455202f022487d33eaa6d30c798fa292ae9cc8c9f7f4fd61593f0d842463a4"
      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.2/pwf_linux_arm64.tar.gz"
      sha256 "4d4cec501f29f170443f4eede4d70d5501dedde187a43c16ad14199a65618584"
      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
  end

  test do
    system "#{bin}/pwf", "--help"
  end
end
