# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwf < Formula
  desc "Personal ProWorkflow CLI"
  homepage "https://github.com/Proactive-Software/pwf-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.0/pwf_darwin_amd64.tar.gz"
      sha256 "1a4274cfd49820c33c8bf58d972f2f00e8c012c7c64faf6fe6e5b43bb9537738"

      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.0/pwf_darwin_arm64.tar.gz"
      sha256 "98f877c518ac6c39afb76a9063a796d3da9c20604f919619193d726f5cc60ece"

      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.0/pwf_linux_amd64.tar.gz"
      sha256 "73507c087ba11dc0e0669ec9d254954eff34529863b2b01c108ccc25c5059261"
      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proactive-Software/pwf-cli/releases/download/v0.2.0/pwf_linux_arm64.tar.gz"
      sha256 "2829362af63bd906e333b0f9593a95fa47ea0693bdbec1fe59c47e3cef80fc75"
      define_method(:install) do
        bin.install "pwf"
        output = Utils.safe_popen_read("#{bin}/pwf", "completion", "zsh")
        (zsh_completion/"_pwf").write output
      end
    end
  end

  test do
    system "#{bin}/pwf", "--help"
  end
end
